<h1>CS4619: Artificial Intelligence 2</h1>
<h2>Background Review</h2>
<h3>
    Derek Bridge<br>
    School of Computer Science and Information Technology<br>
    University College Cork
</h3>

# Initialization $\newcommand{\Set}[1]{\{#1\}}$ $\newcommand{\Tuple}[1]{\langle#1\rangle}$ $\newcommand{\v}[1]{\pmb{#1}}$ $\newcommand{\cv}[1]{\begin{bmatrix}#1\end{bmatrix}}$ $\newcommand{\rv}[1]{[#1]}$

In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import numpy.linalg as npla

<h1>Matrices</h1>
<p>
    A <b>matrix</b> is a rectangular array, in our case of real numbers.
</p>
<ul>
    <li>
        In general, we use bold capital letters, e.g. $\v{A}$, for matrices, e.g.
        $$\v{A} = \begin{bmatrix}
                      2 & 4 & 0 \\
                      1 & 3 & 2
                  \end{bmatrix}
        $$
    </li>
    <li>
        <b>Dimension</b>: A matrix with $m$ rows and $n$ columns is an <b>$m \times n$ matrix</b>
        <ul>
            <li>
                What are $m$ and $n$ for $\v{A}$?
            </li>
        </ul>
    </li>
    <li>
        We refer to an <b>element</b> of a matrix either using subscripts or indexes
        <ul>
            <li>
                $\v{A}_{i,j}$ or $\v{A}[i,j]$ is the element in the $i$th row and $j$th column
            </li>
            <li>
                We will index from 1
                <ul>
                    <li>
                        However, we will sometimes use position 0 for 'technical' purposes
                    </li>
                    <li>
                        And we must be aware that Python numpy arrays and matrices are 0-indexed
                    </li>
                </ul>
             </li>
             <li>
                 So what are $\v{A}_{2,1}$, $\v{A}_{1,2}$, $\v{A}_{0,0}$ and $\v{A}_{3, 2}$?
             </li>
        </ul>
    </li>
</ul>

<h1>Vectors</h1>
<p>
    A <b>vector</b> is a matrix that has only one column, i.e. a $m \times 1$ matrix
</p>
<ul>
    <li>
        A vector with $m$ rows is called a <b>$m$-dimensional</b> vector
    </li>
    <li>
        In general, we use bold lowercase letters for vectors, e.g.
        $$\v{x} = \cv{2\\4\\3}$$
    <li>
        Sometimes this is called a <b>column vector</b>
    </li>
    <li>
        Then, by contrast, a <b>row vector</b> is a matrix that has only one row, i.e. a $1 \times n$ matrix, e.g.
        $$\rv{2, 4, 3}$$
    </li>
    <li>
        Unless stated otherwise, a vector should be assumed to be a column vector.
    </li>
    <li>
        We can refer to an element using a single subscript, again most of the time indexed from 1
        <ul>
            <li>
                So what is $\v{x}_1$?
            </li>
        </ul>
    </li>
</ul>

<h1>Vectors and Matrices in Python</h1>
<p>
    Of the many ways of representing vectors and matrices in Python, we will use two:
</p>
<ul>
    <li>
        From the pandas library, for vectors we will use <code>Series</code>, which are a kind of one-dimensional array,
        and for matrices we will use <code>DataFrame</code>s, which are tabular data structures of rows and columns.
        As well as supporting fairly traditional indexing, the columns in a <code>DataFrame</code> can have names,
        which can also be used to extract data from the <code>DataFrame</code>.
    </li>
    <li>
        From the numpy library, we will use numpy arrays, which can be one-dimensional, two-dimensional, or have
        more dimensions. The machine learning library that we will use, scikit-learn, expects its data to arrive
        as numpy arrays.
    </li>
</ul>  
<p>
    For the rest of this lecture, we'll exemplify numpy arrays.
</p>

<h2>Using numpy arrays</h2>

In [4]:
# Vectors
# We will use a numpy 1d array, which we can create from a list
# But, done this way, there is no way for us to distinguish between column- and row-vectors
x = np.array([2, 4, 3])

# Matrices
# We will use a numpy 2d array, which we can create from a list of lists
A = np.array([[2, 4, 0], [1, 3, 2]])

<h1>Matrix Addition and Subtraction</h1>
<p>
    Two matrices $\v{A}$ and $\v{B}$ can be added or subtracted if they have the same dimensions. 
    Their sum is obtained by adding or subtracting corresponding elements, e.g.
    $$
        \v{A} = \begin{bmatrix}
                2 & 4 & 0 \\
                1 & 3 & 2
            \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
        \v{B} = \begin{bmatrix}
                1 & 0 & 5 \\
                2 & 3 & 2
            \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
        \v{A}+\v{B} = \begin{bmatrix}
                3 & 4 & 5 \\
                3 & 6 & 4
              \end{bmatrix}
    $$
</p>

<h1>Scalar Multiplication</h1>
<p>
    Matrices can be multiplied by real numbers (in this context, often called 'scalars'). The scalar product is obtained
    by multiplying each element by the scalar, e.g.
    $$\v{A} = \begin{bmatrix}
            2 & 4 & 0 \\
            1 & 3 & 2
            \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
      2\v{A} = \begin{bmatrix}
            4 & 8 & 0 \\
            2 & 6 & 4
           \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
      \v{A}/2 = \begin{bmatrix}
            1 & 2 & 0 \\
            0.5 & 1.5 & 1
                \end{bmatrix}
    $$
</p>

<h1>Matrix Addition, Subtraction and Scalar Multiplication in Python</h1>
<p>
    numpy arrays enable operations like these using the normal addition, subtraction and multiplication
    operators and without writing for loops:
</p>

In [5]:
A = np.array([[2, 4, 0], [1, 3, 2]])
B = np.array([[1, 0, 5], [2, 3, 2]])
A + B

array([[3, 4, 5],
       [3, 6, 4]])

<p>
    Similarly, operations with scalars are also applied elementwise:
</p>

In [6]:
2 * A

array([[4, 8, 0],
       [2, 6, 4]])

<h1>Matrix Multiplication</h1>
<p>
    We can compute $\v{A}\v{B}$, the result of multiplying matrices $\v{A}$ and $\v{B}$, provided the number of columns
    of $\v{A}$ equals the number of rows of $\v{B}$
</p>
<ul>
    <li>
        If $\v{A}$ is a $m \times p$ matrix and $\v{B}$ is a $p \times n$ matrix, then we can compute $C = \v{A}\v{B}$
    </li>
    <li>
        $\v{C}$ will be a $m \times n$ matrix
    </li>
    <li>
        $\v{C}_{i,j}$ is obtained by multiplying elements of the $i$th row of $\v{A}$ by corresponding elements
        of the $j$th column of $\v{B}$ and summing:
        $$\v{C}_{i,j} = \sum_{k=1}^p\v{A}_{i,k}\v{B}_{k,j}$$
    </li>
    <li>E.g.
        $$\v{A} = \begin{bmatrix}
                    2 & 4 & 0 \\
                    1 & 3 & 2
                  \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
          \v{B} = \begin{bmatrix}
                    3 & 1 & 2\\
                    2 & 3 & 1\\
                    1 & 3 & 3
                    \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
         \v{A}\v{B} = \begin{bmatrix}
                         14 & 14 & 8\\
                         11 & 16 & 11
                      \end{bmatrix}
         $$
    </li>
    <li>Since vectors are just one-column vectors, matrix multiplication can apply &mdash; provided the dimensions are OK, e.g.
        $$\v{A} = \begin{bmatrix}
                  2 & 4 & 0 \\
                  1 & 3 & 2
                  \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
          \v{x} = \cv{2\\3\\1}\,\,\,\,\,\,\,\,\,\,
          \v{y} = \cv{2\\3}\,\,\,\,\,\,\,\,\,\,
          \v{A}\v{x} = \cv{16\\13}\,\,\,\,\,\,\,\,\,\,
          \v{A}\v{y} \mbox{ is undefined}
        $$
    </li>
</ul> 

<h1>Matrix Multiplication in Python</h1>
<p>
    numpy offers dot as a function or method for matrix multiplication:
</p>

In [7]:
A = np.array([[2, 4, 0], [1, 3, 2]])
B = np.array([[3, 1, 2], [2, 3, 1], [1, 3, 3]])

# Multiplication as a function
# np.dot(A, B)

# Multiplication as a method
A.dot(B)

array([[14, 14,  8],
       [11, 16, 11]])

<p>
    Be warned that A * B on numpy arrays is <strong>not</strong> the same as matrix multiplication as defined
    above. Instead, it is performed elementwise on corresponding elements of two equal-sized arrays.
</p>

<h1>Transpose</h1>
<p>
    The <b>transpose</b> of $m \times n$ matrix $\v{A}$, written $\v{A}^T$, is the $n \times m$ matrix in 
    which the first row of $\v{A}$ becomes the first column of $\v{A}^T$, the second row of $\v{A}$ becomes 
    the second column of $\v{B}$, and so on.
</p>
<ul>
    <li>
        $\v{A}_{i,j}^T = \v{A}_{j,i}$
    </li>
    <li>
        E.g.
        $$\v{A} = \begin{bmatrix}
                2 & 4 & 0 \\
                1 & 3 & 2
              \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
          \v{A}^T = \begin{bmatrix}
                     2 & 1 \\
                     4 & 3 \\
                     0 & 2
                    \end{bmatrix}
        $$
    </li>
    <li>
        As a special case, if $\v{x}$ is a $m$-dimensional column vector ($m \times 1$), then $\v{x}^T$ is a 
        $m$-dimensional row vector ($1 \times m$), e.g.
        $$\v{x} = \cv{2\\4\\3}\,\,\,\,\,\,\,\,\,\, \v{x}^T = \rv{2, 4, 3}$$
    </li>
</ul>

<h1>Transpose in Python</h1>
<p>
    numpy arrays offer easy ways to compute their transpose: either the transpose method or the T attribute:
</p>

In [8]:
A = np.array([[2, 4, 0], [1, 3, 2]])

# Transpose as a method
# A.transpose()

# Tranpose as an attribute
A.T

array([[2, 1],
       [4, 3],
       [0, 2]])

<h1>Identity Matrices</h1>
<p>
    The $n \times n$ <b>identity matrix</b>, $\v{I}_n$, contains zeros except for entries on the main diagonal
    (from top left to bottom right).
</p>
<ul>
    <li>
        $\v{I}_n[i,i] = 1$ for $i = 1,\ldots,n$ and $\v{I}_n[i,j] = 0$ for $i \neq j$, e.g.
        $$\v{I}_3 = \begin{bmatrix}
                    1 & 0 & 0 \\
                    0 & 1 & 0 \\
                    0 & 0 & 1
                    \end{bmatrix}
        $$
    </li>
    <li>
        If $\v{A}$ is an $m \times n$ matrix then, $\v{A}\v{I}_n = \v{I}_m\v{A} = \v{A}$
    </li>
</ul>

<h1>Inverses</h1>
<p>
    If $\v{A}$ is a $n \times n$ matrix, then its <b>inverse</b>, $\v{A}^{-1}$ (<em>if it has one</em>) is also 
    a $n \times n$ matrix such that $\v{A}\v{A}^{-1} = \v{I}_n$.
</p>
<ul>
    <li>
        $\v{A} = \begin{bmatrix}
                    1 &  0 & 2 \\
                    2 & -1 & 3 \\
                    4 &  1 & 8
                 \end{bmatrix}\,\,\,\,\,\,\,\,\,\,
         \v{A}^{-1} = \begin{bmatrix}
                     -11 &  2 &  2 \\
                      -4 &  0 &  1 \\
                       6 & -1 & -1
                      \end{bmatrix}
        $
    </li>
    <li>
        Some $n \times n$ matrices do not have inverses, e.g.
        $$\begin{bmatrix}
            1 & 1 & 1 \\
            1 & 1 & 1 \\
            1 & 1 & 1
           \end{bmatrix}$$
        In these cases, provided the matrix is square, you can compute a pseudo-inverse, which you can use 
        for <em>some</em> of the same purposes instead
    </li>
</ul>

<h1>Inverses in Python</h1>
<p>
    numpy.linalg offers function inv for computing inverses, but also function pinv for computing the 
    Moore-Penrose pseudo-inverse:
</p>

In [9]:
A = np.array([[1, 0, 2], [2, -1, 3], [4, 1, 8]])

npla.inv(A)

array([[ -1.10000000e+01,   2.00000000e+00,   2.00000000e+00],
       [ -4.00000000e+00,  -2.96059473e-16,   1.00000000e+00],
       [  6.00000000e+00,  -1.00000000e+00,  -1.00000000e+00]])

In [10]:
npla.pinv(A)

array([[ -1.10000000e+01,   2.00000000e+00,   2.00000000e+00],
       [ -4.00000000e+00,   1.41990266e-14,   1.00000000e+00],
       [  6.00000000e+00,  -1.00000000e+00,  -1.00000000e+00]])

In [11]:
B = np.ones((3,3))

npla.inv(B) # raises an exception

LinAlgError: Singular matrix

In [13]:
npla.pinv(B)

array([[ 0.11111111,  0.11111111,  0.11111111],
       [ 0.11111111,  0.11111111,  0.11111111],
       [ 0.11111111,  0.11111111,  0.11111111]])

<h1>Vectorization</h1>
<p>
    Algorithms that might otherwise need for-loops can often be written much more succinctly by expressing them
    in terms of matrix operations. More than this, if your programming language has efficient implementations of
    these operations, the resulting programs can run much faster too. 
</p>
<p>
    Using fast matrix operations in this way is known as <b>vectorization</b>.
</p>
<p>
    numpy's vectorized array operations, for example, are typically one or more orders of magnitude faster than their 
    pure Python equivalents.
</p>
<p>
    Here are a few more examples.
</p>

<h2>Evaluating a Linear Equation</h2>
<p>
    Suppose you have a linear equation, i.e. of this form:
    $$y = \v{\beta}_1\v{x}_1 + \v{\beta}_2\v{x}_2 + \ldots + \v{\beta}_n\v{x}_n$$
</p>
<ul>
    <li>
        $\ldots$ lots of little multiplications, all added together
    </li>
</ul>
<p>
    You know that this can be written in this form:
    $$y = \sum_{i=1}^n \v{\beta}_i\v{x}_i$$
    If you had to write code to implement this, you might be thinking of a for-loop.
</p>
<p>
    But if we assume that $\v{x}$ is an $n$-dimensional row vector and $\v{\beta}$ is an $n$-dimensional
    column vector, then we can instead write the equation in this form:
    $$y = \v{x}\v{\beta}$$
    and you can implement this with the numpy library's matrix multiplication method.
</p>
<p>
    Let's make this more concrete. Suppose we have this linear equation:
    $$y = 3\v{x}_1 + 2\v{x}_2 + 4\v{x}_4$$
    and we want to evaluate it for $\v{x} = \rv{5, 1, 3}$
</p>
<p>
    We take the coefficients to give us $\v{\beta} = \cv{3\\2\\4}$ and now we compute
    $$y = \rv{5, 1, 3}\cv{3\\2\\4} = 29$$
</p>

<h2>Evaluating a Linear Equation in Python</h2>

In [12]:
beta = np.array([3, 2, 4])
x = np.array([5, 1, 3])

# Evaluate the linear equation - without a for-loop
y = x.dot(beta)

# Display y
y

29

<h2>Evaluating a Linear Equation Multiple Times</h2>
<p>
    Suppose we want to evaluate the linear equation $y = \v{\beta}_1\v{x}_1 + \v{\beta}_2\v{x}_2 + \ldots +
    \v{\beta}_n\v{x}_n$ on a number of different row vectors, first for $\rv{5, 1, 3}$, then for $\rv{2, 6, 2}$,
    then for $\rv{3, 3, 3}$, and finally for $\rv{3, 3, 5}$. Maybe you're thinking of a for-loop again? 
</p>
<p>
    Instead, we put these different row vectors into a single matrix $\v{X}$
    $$\v{X} = \begin{bmatrix}
                5 & 1 & 3 \\
                2 & 6 & 2 \\
                3 & 3 & 3 \\
                3 & 3 & 5
              \end{bmatrix}
    $$
    And we simply evaluate
    $$\v{y} = \v{X}\v{\beta}$$<br>
    $$\v{y} = \begin{bmatrix}
                5 & 1 & 3 \\
                2 & 6 & 2 \\
                3 & 3 & 3 \\
                3 & 3 & 5
              \end{bmatrix}
          \times \cv{3\\2\\4} = \cv{29\\ 26\\ 27\\ 35}
    $$
</p>

<h2>Evaluating a Linear Equation Multiple Times in Python</h2>

In [34]:
beta = np.array([3, 2, 4])
X = np.array([[5, 1, 3], [2, 6, 2], [3, 3, 3], [3, 3, 5]])

# Evaluate the linear equation multiple times - without a for-loop!
y = X.dot(beta)

# Display y
y

array([29, 26, 27, 35])